name: Tailscale Native SSH

on:
  workflow_dispatch:

jobs:
  ssh-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TS_KEY }}
          args: --ssh

      - name: Check Tailscale
        run: |
          tailscale status
          echo "IP:"
          tailscale ip -4
          echo "SSH:"
          tailscale ssh --help

      - name: Keep Runner Alive
        run: tail -f /dev/null
